apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-web
  template:
    metadata:
      labels:
        app: client-web
    spec:
      containers:
        - name: client-web
          image: farul672/client-nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
