apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      containers:
        - name: schedule-app
          image: farul672/schedule-app:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: schedule-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
