apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-web
  template:
    metadata:
      labels:
        app: catalog-web
    spec:
      containers:
        - name: catalog-web
          image: farul672/catalog-nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
