apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-app
  template:
    metadata:
      labels:
        app: catalog-app
    spec:
      containers:
        - name: catalog-app
          image: farul672/catalog-app:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: catalog-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
